spring:
  application:
    name: StatisticService
  datasource:
    url: ${PM_DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  liquibase:
    change-log: db.changelog/changelog.xml
  jpa:
    hibernate:
      ddl-auto: none

pm:
  service:
    url: http://localhost:8888